"""2025-03-20

Revision ID: 59fc60ff83b0
Revises: b95cf2d72014
Create Date: 2025-03-20 12:07:24.859012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59fc60ff83b0'
down_revision: Union[str, None] = 'b95cf2d72014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_session', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('conversation_session', sa.Column('user_email', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'conversation_session', 'project_table', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_session', 'user_table', ['user_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_session', type_='foreignkey')
    op.drop_constraint(None, 'conversation_session', type_='foreignkey')
    op.drop_column('conversation_session', 'user_email')
    op.drop_column('conversation_session', 'project_id')
    # ### end Alembic commands ###
