"""2025-03-20-1

Revision ID: 8d4dd4c6bb8c
Revises: 59fc60ff83b0
Create Date: 2025-03-20 14:49:15.888412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '8d4dd4c6bb8c'
down_revision: Union[str, None] = '59fc60ff83b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_info_base', 'vector_memory',
               existing_type=postgresql.ARRAY(sa.INTEGER()),
               type_=Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_info_base', 'vector_memory',
               existing_type=Vector(dim=1536),
               type_=postgresql.ARRAY(sa.INTEGER()),
               existing_nullable=True)
    # ### end Alembic commands ###
