"""2025-03-26

Revision ID: 99277c87e2d3
Revises: 58f67940ea57
Create Date: 2025-03-26 18:02:00.686869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99277c87e2d3'
down_revision: Union[str, None] = '58f67940ea57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['provider_table.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('AI_Models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AI_Models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_table.id'], name='AI_Models_provider_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_name'], ['provider_table.name'], name='AI_Models_provider_name_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='AI_Models_pkey')
    )
    op.drop_table('ai_models')
    # ### end Alembic commands ###
