"""2025-03-20-2

Revision ID: d462be2b4153
Revises: 8d4dd4c6bb8c
Create Date: 2025-03-20 15:32:45.362070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd462be2b4153'
down_revision: Union[str, None] = '8d4dd4c6bb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_info_base', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_info_base', sa.Column('file', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
