"""2025-03-19

Revision ID: ed715b7efade
Revises: 03930cf2be1a
Create Date: 2025-03-19 16:27:30.461563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed715b7efade'
down_revision: Union[str, None] = '03930cf2be1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key_table', sa.Column('provider_name', sa.String(length=255), nullable=False))
    op.create_foreign_key(None, 'api_key_table', 'provider_table', ['provider_name'], ['name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_key_table', type_='foreignkey')
    op.drop_column('api_key_table', 'provider_name')
    # ### end Alembic commands ###
